name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
    steps:
      -
        uses: actions/checkout@v1
      -
        name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      -
        name: Build
        run: "npm install\nnpm run build\nnpm run predeploy\n"
      -
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          REACT_APP_MOVIEDB_API_KEY: '${{ secrets.REACT_APP_MOVIEDB_API_KEY }}'
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
          BRANCH: gh-pages
          FOLDER: build
